name: Backend CI/CD - EC2

on:
  push:
    branches:
      - main
    paths:
      - "ecom_proj/backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/ecom-frontend-backend-integration
            git pull origin main

            cd ecom_proj/backend
            npm install

            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PORT=5000" >> .env

            pm2 restart backend || pm2 start server.js --name backend
            pm2 save
